### ISSUE TITLE
Is Remix Streaming Working?

### ISSUE THREAD

**Issue by rjvim** [jherr/react-streaming#2]
To prove that streaming is working in diy-version, you have made an curl call `curl --no-buffer http://localhost:3000` and the response comes in "parts" - I am assuming that proves that HTML was streamed.

But when I tried the same in "remix-version", it was sending response at once.

I have replaced comments fetching with a real api, and network tab doesn't show any XHR calls, so, the content is served from server side. Is `curl --no-buffer` as consistent way to test React Streaming SSR? What's the best way to prove that content is being streamed?

Please advice.

**Comment by jherr** [comment]
It's possible remix has changed, it does fairly frequently. If you want
streamed remix I recommend taking a look at the Remix examples repo or
jumping on the Remix Discord.

**Comment by rjvim** [comment]
@jherr Confirming. The way to test streaming is `curl --no-buffer`

But in my code there was `isbot(request.headers.get("user-agent"))`, which doesn't stream when tried via curl.
